//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmobile.Explore.Web.CostCalculator {
    
    
    public partial class Default {
        
        /// <summary>
        /// ResourceManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Tmobile.Framework.Presentation.Controls.ResourceManager ResourceManager1;
        
        /// <summary>
        /// ResourceManagerFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Tmobile.Framework.Presentation.Controls.ResourceManager ResourceManagerFooter;
        
        /// <summary>
        /// Script1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Tmobile.Framework.Presentation.Controls.Script Script1;
        
        /// <summary>
        /// Script2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Tmobile.Framework.Presentation.Controls.Script Script2;
        
        /// <summary>
        /// Script3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Tmobile.Framework.Presentation.Controls.Script Script3;
        
        /// <summary>
        /// Script4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Tmobile.Framework.Presentation.Controls.Script Script4;
    }
}
